### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by zephyrus23** [niallobrien/generator-gulp-foundation#16]
After running the command `gulp`, the following error was returned:
![gulp-error](https://cloud.githubusercontent.com/assets/11275324/8235530/c6acd94e-159f-11e5-8697-991c4e7694d1.png)

**Comment by etx** [comment]
I just had the same issue.
* In package.json set browser-sync version to ~2.7.1 then npm install
* in gulpfile.js line 91 I changed it to ``require('opn')(bs.options.get('urls').get('local'));``

**Comment by mininao** [comment]
Same here. I'll try to do a pull request

**Comment by niallobrien** [comment]
I appreciate the PR guys, I honestly don't use my gulp Bootstrap or Foundation generators anymore but thought others might appreciate a solid foundation to fork from.

**Comment by awojtczyk** [comment]
There is simpler fix: navigate to node_modules/browser-sync/packages.json and change http-proxy version to 1.11.0, then npm install in browser sync directory.
